var configOptions = {
    "group": "908dd46e749d4565a17d2b646ace7b1a",
    "appid": "",
    "theme": "blueTheme",
    "siteTitle": "My Maps",
    "siteBannerImage": "",
    "mapTitle": "",
    "mapSnippet": "",
    "mapItemDescription": "",
    "mapLicenseInfo": "",
    "homeHeading": "",
    "homeSnippet": "",
    "homeSideHeading": "Description",
    "homeSideContent": "",
    "footerHeading": "",
    "footerDescription": "",
    "footerLogo": "",
    "footerLogoUrl": "",
    "addThisProfileId": "xa-4f3bf72958320e9e",
    "defaultLayout": "grid",
    "searchString": "",
    "sortField": "modified",
    "sortOrder": "desc",
    "searchType": "Maps",
    "mapViewer": "simple",
    "galleryItemsPerPage": 9,
    "showProfileUrl": false,
    "showAboutPage": false,
    "showSocialButtons": true,
    "showFooter": true,
    "showBasemapGallery": true,
    "showGroupSearch": true,
    "showGroupSort": false,
    "showMapSearch": true,
    "showLayerToggle": true,
    "showLayoutSwitch": true,
    "showOverviewMap": true,
    "showMoreInfo": false,
    "showPagination": true,
    "showExplorerButton": false,
    "showArcGISOnlineButton": false,
    "showLicenseInfo": true,
    "showAttribution": true,
    "showComments": true,
    "showRatings": true,
    "showViews":true,
    "showMobileButtons": true,
    "openGalleryItemsNewWindow": false,
    "bannerBackground": "images/ui/banner.png",
    "bingMapsKey": "",
    "locatorserviceurl": "http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer",
    "geometryserviceurl": "http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer",
    "proxyUrl":"proxy/proxy.php",
    "sharingurl":"http://www.arcgis.com/sharing/rest/content/items",
    "portalUrl":"http://www.arcgis.com/",
    "mobilePortalUrl":"arcgis://www.arcgis.com/",
    "iosAppUrl": "itms://itunes.apple.com/us/app/arcgis/id379687930?mt=8",
    "androidAppUrl": "https://market.android.com/details?id=com.esri.android.client",
    "pointGraphic": "images/ui/bluepoint-21x25.png",
	"sourceCountry":"USA"
};