var configOptions = {
   "group":{
      "id":"",
      "title":"National Maps for USA",
      "owner":"Federal_User_Community"
   },
   "appid":"",
   "theme":"blueTheme",
   "siteTitle":"My Gallery",
   "siteBannerImage":"images/yourLogo.png",
   "mapTitle":"",
   "mapSnippet":"",
   "mapItemDescription":"",
   "homeHeading":"",
   "homeSnippet":"",
   "homeSideHeading":"Description",
   "homeSideContent":"",
   "footerHeading":"Footer Text",
   "footerDescription":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi facilisis dapibus odio a gravida. Proin orci libero, laoreet nec blandit nec, placerat non massa. Suspendisse nunc turpis, imperdiet id consequat vel, ornare eu lectus. In sit amet blandit justo.",
   "footerLogo":"",
   "footerLogoUrl":"",
   "addThisProfileId":"xa-4f3bf72958320e9e",
   "defaultLayout":"grid",
   "sortField":"uploaded",
   "sortOrder":"desc",
   "mapViewer":"simple",
   "galleryItemsPerPage":9,
   "showProfileUrl":true,
   "showAboutPage":true,
   "showSocialButtons":true,
   "showFooter":true,
   "showBasemapGallery":true,
   "showGroupSearch":true,
   "showMapSearch":true,
   "showLayerToggle":true,
   "showLayoutSwitch":true,
   "showOverviewMap":true,
   "showMoreInfo":true,
   "showMobileDialog":true,
   "showPagination":true,
   "showExplorerButton":true,
   "showArcGISOnlineButton":true,
   "openGalleryItemsNewWindow":false,
   "mobileAppUrl":true,
   "bingmapskey":"Akt3ZoeZ089qyG3zWQZSWpwV3r864AHStal7Aon21-Fyxwq_KdydAH32LTwhieA8",
   "proxyurl":"",
   "locatorserviceurl":"http://tasks.arcgis.com/ArcGIS/rest/services/WorldLocator/GeocodeServer/",
   "geometryserviceurl":"http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer",
   "sharingurl":"http://www.arcgis.com/sharing/rest/content/items",
   "portalUrl":"http://www.arcgis.com/",
   "mobilePortalUrl":"arcgis://www.arcgis.com/",
   "iosAppUrl":"itms://itunes.apple.com/us/app/arcgis/id379687930?mt=8",
   "androidAppUrl":"https://market.android.com/details?id=com.esri.android.client",
   "pointGraphic":"images/ui/bluepoint-21x25.png"
};